---
version: "2"

services:
  web:
    image: jwilder/nginx-proxy:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      ENABLE_IPV6: 'true'
      DHPARAM_GENERATION: 'false'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/vhost:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
    networks:
      - app

  acme:
    image: nginxproxy/acme-companion:latest
    container_name: acme-companion
    restart: always
    environment:
      DEFAULT_EMAIL: ${YOUR_EMAIL}
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/vhost:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme:/etc/acme.sh
    networks:
      - app

  nextcloud:
    image: nextcloud:20.0.14
    container_name: nextcloud
    restart: always
    environment:
      NEXTCLOUD_TRUSTED_DOMAINS: ${YOUR_DOMAIN}
      LETSENCRYPT_HOST: ${YOUR_DOMAIN}
      VIRTUAL_HOST: ${YOUR_DOMAIN}
      OVERWRITEPROTOCOL: https
    volumes:
      - ./nextcloud:/var/www/html
    networks:
      - app

networks:
  app:
    driver: bridge
